# Generated by Django 4.2.1 on 2023-06-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MESSAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(max_length=200, verbose_name='тема письма')),
                ('letter_body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='SETTINGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='начало рассылки')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='конец рассылки')),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, null=True)),
                ('status', models.CharField(max_length=50, verbose_name='статус рассылки')),
                ('clients', models.ManyToManyField(blank=True, null=True, to='mailing_list.client', verbose_name='клиенты')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing_list.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='ATTEMPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('server_answer', models.BooleanField(blank=True, null=True, verbose_name='ответ сервера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_list.message', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
    ]
