# Generated by Django 4.2.1 on 2023-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_client_author_settings_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='last_run',
            field=models.DateField(blank=True, null=True, verbose_name='дата последней отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='конец рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='начало рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('LAUNCHED', 'Запущена'), ('COMPLETED', 'Завершена')], max_length=50, verbose_name='статус рассылки'),
        ),
    ]
