# Generated by Django 4.2.1 on 2023-07-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0003_settings_last_run_alter_settings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'permissions': [('can_deactivate_settings', 'Can deactivate settinngs')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
