# Generated by Django 4.2.1 on 2023-07-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0006_alter_attempt_server_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing_list.settings', verbose_name='рассылка'),
        ),
    ]
