# Generated by Django 4.2.1 on 2023-07-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0007_attempt_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='clients',
            field=models.ManyToManyField(to='mailing_list.client', verbose_name='клиенты'),
        ),
    ]
