# Generated by Django 4.2.1 on 2023-07-07 9:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='заблокирован ли пользователь'),
        ),
    ]
