# Generated by Django 4.2.1 on 2023-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_block',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='активность'),
        ),
    ]
